// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DownloadAndApplyUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndApplyUpdate'](arg1);
}

export function GetKatPluginsState() {
  return window['go']['main']['App']['GetKatPluginsState']();
}

export function GetLolConfigState() {
  return window['go']['main']['App']['GetLolConfigState']();
}

export function HandleKatPluginsMainAction() {
  return window['go']['main']['App']['HandleKatPluginsMainAction']();
}

export function InstallAccountManager() {
  return window['go']['main']['App']['InstallAccountManager']();
}

export function OpenAccountManager() {
  return window['go']['main']['App']['OpenAccountManager']();
}

export function ShowDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowDialog'](arg1, arg2, arg3);
}

export function ToggleLolConfig(arg1) {
  return window['go']['main']['App']['ToggleLolConfig'](arg1);
}

export function UninstallKatPlugins() {
  return window['go']['main']['App']['UninstallKatPlugins']();
}
