// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {katplugins} from '../models';
import {lolconfig} from '../models';

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function DownloadAndApplyUpdate(arg1:string):Promise<void>;

export function GetKatPluginsState():Promise<katplugins.KatPluginsInfo>;

export function GetLolConfigState():Promise<lolconfig.LolConfigInfo>;

export function HandleKatPluginsMainAction():Promise<boolean>;

export function InstallAccountManager():Promise<boolean>;

export function OpenAccountManager():Promise<void>;

export function ShowDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleLolConfig(arg1:boolean):Promise<boolean>;

export function UninstallKatPlugins():Promise<boolean>;
